services: 
  api:
    build: .
    container_name: api-teste
    ports:
      - "3000:3000" 
    networks:
      - minha-rede

  db:
    image: postgres:15-alpine
    container_name: db-teste
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-teste
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  postgres-data:  

